
export enum ACTION_TYPES {
    FETCH_SNEAKERS_LIST='@@SNEAKERS/FETCH_SNEAKERS_LIST',
    SET_SNEAKERS_LIST='@@SNEAKERS/SET_SNEAKERS_LIST',
    GET_SNEAKER='@@SNEAKERS/GET_SNEAKER',
    SET_SNEAKER='@@SNEAKERS/SET_SNEAKER',
    SORT_POPULAR='@@SNEAKERS/SORT_POPULAR',
    GET_MOST_POPULAR='@@SNEAKERS/GET_MOST_POPULAR',
    SET_MOST_POPULAR='@@SNEAKERS/SET_MOST_POPULAR'
}