
export enum ACTION_TYPES {
    FETCH_SNEAKERS_LIST='@@SNEAKERS/FETCH_SNEAKERS_LIST',
    SET_SNEAKERS_LIST='@@SNEAKERS/SET_SNEAKERS_LIST',

    GET_SNEAKERS_BY_GENDER='@@SNEAKERS/GET_SNEAKERS_BY_GENDER',
    SET_SNEAKERS_BY_GENDER='@@SNEAKERS/SET_SNEAKERS_BY_GENDER',

    GET_SNEAKERS_BY_BRAND='@@SNEAKERS/GET_SNEAKERS_BY_BRAND',
    
    SORT_POPULAR='@@SNEAKERS/SORT_POPULAR',
    GET_MOST_POPULAR='@@SNEAKERS/GET_MOST_POPULAR',
    SET_MOST_POPULAR='@@SNEAKERS/SET_MOST_POPULAR'
}