
export enum ACTION_TYPES {
    GET_IS_SIGNED_IN='@@AUTH/GET_IS_SIGNED_IN',
    SET_IS_SIGNED_IN='@@AUTH/SET_IS_SIGNED_IN',
    GET_USER_LIST='@@AUTH/GET_USER_LIST',
    SET_USER_LIST='@@AUTH/SET_USER_LIST',
    GET_USER_BY_EMAIL='@@AUTH/GET_USER_BY_EMAIL',
    GET_ACTIVE_USER='@@AUTH/GET_ACTIVE_USER',
    SET_ACTIVE_USER='@@AUTH/SET_ACTIVE_USER',
    ADD_USER='@@AUTH/ADD_USER',
    VERIFY_SIGNIN_VALIDATION='@@AUTH/VERIFY_SIGNIN_VALIDATION',
    SET_SIGNIN_VALIDATION_ERROR='@@AUTH/SET_SIGNIN_VALIDATION_ERROR',
    LOG_OUT='@@AUTH/LOG_OUT'
}