
export enum ACTION_TYPES {
    GET_CART_LIST='@@CART/GET_CART_LIST',
    SET_CART_LIST='@@CART/SET_CART_LIST',
    ADD_CART_ITEM='@@CART/ADD_CART_ITEM',
    DELETE_CART_ITEM='@@CART/DELETE_CART_ITEM',
    SET_TOTAL_PRICE='@@CART/SET_TOTAL_PRICE'
}